### ISSUE TITLE
Airflow tutorial problem

### ISSUE THREAD

**Issue by idomic** [ploomber/soopervisor#23]
After cloning the repo, the cd path is wrong, no such path ./projects/ml-intermediate.

I assume it's this path here:
https://github.com/ploomber/projects/search?q=ml-intermediate

**Comment by edublancas** [comment]
oh yes. this broke when I updated the layout in the `ploomber/projects` repo, we need a way of checking for these types of issues. Can you open a PR?

**Comment by idomic** [comment]
I'll open a PR for these specifically and then we can research for common solutions for this issues.

**Comment by edublancas** [comment]
this is fixed in the new tutorial
