### ISSUE TITLE
AWS Airflow tutorial problem - pipeline.yaml clients indented

### ISSUE THREAD

**Issue by idomic** [ploomber/soopervisor#24]
Inside pipeline.yaml, when uncomenting the clients it becomes a part of the meta scope.

Instead of

meta:
    ...
clients:
    ...

The user sees an error since it's uncommented like this:
meta:
    ...
    clients:
        ...

**Comment by edublancas** [comment]
this depends on how you un-comment, I did it with the editor's shortcut and it worked fine. but if you uncomment manually then, as you mentioned, this breaks. I fixed it https://github.com/ploomber/projects/blob/master/templates/ml-intermediate/pipeline.yaml
