### ISSUE TITLE
Airflow tutorial problem - supervisor.yaml

### ISSUE THREAD

**Issue by idomic** [ploomber/soopervisor#25]
After setting the .yaml file,

soopervisor export train start running the dockerfile and errors out:

executor failed running [/bin/sh -c mamba env update --name base --file project/environment.lock.yml && conda clean --all --force-pkgs-dir --yes]: exit code: 1

#7 15.91 Encountered problems while solving:
#7 15.91   - package mamba-0.11.3-py39h951de11_0 requires openssl >=1.1.1k,<1.1.2a, but none of the providers can be installed
#7 15.91

**Comment by edublancas** [comment]
I think this is a problem with mamba/conda, I ran into this when running some example, but I can't remember how I fixed it

**Comment by edublancas** [comment]
this is fixed in the new tutorial
