### ISSUE TITLE
Tests and artifacts misorganized

### ISSUE THREAD

**Issue by idomic** [ploomber/soopervisor#28]
In the soopervisor/src/soopervisor/assets/
argo should have it's own folder: argo-workflow.yaml

Same thing happens in the tests folder for argo and airflow.

For both we need to move the files into the right location, make sure the path it's consumed from is updated in the code and check the tests are still passing.

**Comment by edublancas** [comment]
fixed in ddb9f4e3185dfd401ff9526046dace00245b5cd0
