### ISSUE TITLE
add section on product parametrization to docs

### ISSUE THREAD

**Issue by edublancas** [ploomber/soopervisor#44]
Our examples use the ml-intermediate pipeline which already parametrizes products, so users only need to add the `env.yaml` and run it. https://soopervisor.readthedocs.io/en/latest/tutorials/kubernetes.html

However, if they try a different example, it will break. so we need to add a section where we explain how to parameterize a pipeline

**Comment by edublancas** [comment]
context: add a brief description in the docs and link to here

https://docs.ploomber.io/en/latest/user-guide/parametrized.html

**Comment by qixuan27** [comment]
I want to clarify what to do about this issue. Is https://docs.ploomber.io/en/latest/user-guide/parametrized.html the exact documentation I need to update? The contents I need to add are a section where we explain how to parameterize a pipeline to users and the link to https://docs.ploomber.io/en/latest/user-guide/parametrized.html. Is that right?

**Comment by edublancas** [comment]
the document to update is this: https://soopervisor.readthedocs.io/en/latest/tutorials/kubernetes.html

the source code is here: https://github.com/ploomber/soopervisor/blob/master/doc/tutorials/kubernetes.rst

essentially, we want to provide guidelines for users who may want to experiment a bit more with the kubernetes integration. The existing tutorial uses ml-intermediate, but now let's say I want to use ml-basic (https://github.com/ploomber/projects/tree/master/templates/ml-basic).

This issue is actually simple, it's just explaining how to adapt other examples so they can be executed with the kubernetes integration.

I'd suggest running the full kubernetes tutorial to become familiar with it, then try running a different example (try with ml-basic) and you'll see that it'll fail - the purpose is to describe to the user how they can adapt other examples so they run. the answer is to introduce them to the concept of parametrized pipelines, so having a short description of what parametrized pipelines are is enough, and then linking to https://docs.ploomber.io/en/latest/user-guide/parametrized.html - which expands on the subject

also, we've seen that users are struggling to follow the kubernetes tutorial, so anything you can contribute to simplifying it with clear instruction is also helpful!

**Comment by qixuan27** [comment]
Thanks for your instructions! That's really helpful. I have run the tutorial and tried the ml-basic example. Only one question: in the source code file (https://github.com/ploomber/soopervisor/blob/master/doc/tutorials/kubernetes.rst), there are only several lines for the contents at the very beginning of the .HTML file. Should I update all information of the .HTML file into the .rst file first, then add section on product parametrization in the updated .rst file?

**Comment by edublancas** [comment]
I'm unsure if I'm following your questions. I think you're asking about the difference between .rst and .html.

.rst are the source files, those are the ones we should edit, the .html ones are generated from the .rst ones [using this command](https://github.com/ploomber/soopervisor/blob/master/CONTRIBUTING.md#viewing-the-docstutorials)

[kubernetes.rst](https://raw.githubusercontent.com/ploomber/soopervisor/master/doc/tutorials/kubernetes.rst) only has a few lines because it's importing its content from two other files

https://github.com/ploomber/soopervisor/blob/master/doc/tutorials/_k8s-local.rst

and

https://github.com/ploomber/soopervisor/blob/master/doc/tutorials/_k8s-gc.rst

**Comment by edublancas** [comment]
does this help?

**Comment by qixuan27** [comment]
That's very helpful. Thanks!

**Comment by idomic** [comment]
Merged
