### ISSUE TITLE
error in cp_ploomber_home

### ISSUE THREAD

**Issue by edublancas** [ploomber/soopervisor#63]
it replaces the `.tar.gz` instead of adding the new files, added a test case in the `cp-ploomber-home` branch

**Comment by edublancas** [comment]
I disabled the call to `cp_ploomber_home` until we find a fix. I found that Python doesn't support appending to tar.gz files https://stackoverflow.com/questions/30981165/add-files-to-tar-in-python

**Comment by idomic** [comment]
It does under a certain flags.. Play with it a bit. How's the tests passing
if the files aren't there?

**Comment by edublancas** [comment]
I tried changing the flags, it doesn't work (check the SO link), it's not supported.

the files passed because the only test that we have checks that the config files are there, but it doesn't check that the rest of the source code is there - I added one new test to check that

**Comment by idomic** [comment]
So why do we want this as part of the tar and not simply in the folder like it was before the change? the files did get copied to a dir and then into the image. It's either that or unzipping and zipping the tar file

**Comment by edublancas** [comment]
Yes, I think that's the way to go.

A few notes:

1. the function that copies the user's code into the image copies all the project's file tree so anything under it will go to the docker image
2. the `env_name/` directory contains config files that aren't needed for running the pipeline in docker, the fact that it ends up in the docker image is a consequence of the previous point, but that's fine, we can use this as kind of "staging" area for preparing the files to copy

My suggestion is that we should create a temporary directory within `env_name/` with the files that we want to put in the docker image. so if the project looks like this:

```
env_name/
    Dockerfile
```

During `soopervisor export` will look like this:

```
env_name/
  Dockerfile
  tmp/
     # put everything here - for now it'll only have a copy of  ~/.ploomber/stats
     .ploomber/config/stats
```

Do not copy `~/.ploomber/examples`, since that will make the image unnecessarily larger

**Comment by edublancas** [comment]
fixed this
