### ISSUE TITLE
Kubernetes tutorial Docker image does not build 

### ISSUE THREAD

**Issue by bmwilly** [ploomber/soopervisor#76]
I'm trying to run the [soopervisor kubernetes tutorial](https://soopervisor.readthedocs.io/en/latest/tutorials/kubernetes.html) and have so far run into two issues trying to build the docker image. 

1. `RUN pip install ploomber soopervisor` fails with build errors trying to install `psutil`. I can bypass this by adding the command `RUN conda install -y psutil` before this line (it fails if trying to install with `pip`). 

2. `RUN ploomber examples -f -n templates/ml-intermediate -o mli` fails with 
```
#23 2.220 Please add your email to get updates and support (type enter to skip):
#23 2.515 Error: EOF when reading a line
```

because it's an interactive command. 

If possible, I'd recommend publishing a working image somewhere (like Docker Hub). A much lower barrier to entry for newcomers.

**Comment by edublancas** [comment]
Hi, thanks for the feedback.

We don't have psutil as a direct dependency so it's probably coming indirectly from one of our dependencies.

When we added the email prompt we were debating about this; I think we'll move the prompt out of the examples command and put it in the new interactive onboarding tutorial. In the meantime, you can `git clone https://github.com/ploomber/projects` and get the example that you're looking for from there, under the hood, `ploomber examples` is doing that.

**Comment by bmwilly** [comment]
@edublancas great, thanks. I'll close this out then.

**Comment by edublancas** [comment]
FYI: in the latest release, we removed the email prompt from the `ploomber examples` and put it in our new onboarding tutorial, so this shouldn't be a problem anymore
